name: 'Prepare new PR'
on:
  pull_request_target:
    types: [opened, reopened]
    branches: [ 'main*' ]

jobs:
  prepare-new-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.repository_owner == 'open-telemetry' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run prepare-new-pr.sh
        run: ./.github/workflows/scripts/prepare-new-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
