name: 'Prepare new PR'
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [ 'main*' ]
    paths: ['.chloggen/*']

jobs:
  get-change-details:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    #if: ${{ github.repository_owner == 'open-telemetry' }}
    outputs:
      change_type: ${{ steps.get-change-type.outputs.change_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - id: get-change-type
        name: Run get-change-type.sh
        run: |
          change_type=$(./.github/workflows/scripts/get-change-type.sh)
          echo "change_type=$change_type" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}

  prepare-new-pr:
    runs-on: ubuntu-latest
    needs: get-change-details
    permissions:
      pull-requests: write
    #if: ${{ github.repository_owner == 'open-telemetry' }}
    if: ${{ needs.get-change-details.outputs.change_type != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set label on PR
        run: gh pr edit "${PR}" --add-label "${CHANGE_TYPE}" || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
          CHANGE_TYPE: ${{ needs.get-change-details.outputs.change_type }}
