name: 'Prepare new PR'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  prepare-new-pr:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'open-telemetry' }}
    steps:
      - uses: actions/checkout@v4

      - name: Run prepare-new-pr.sh
        run: ./.github/workflows/scripts/prepare-new-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
